name: PR Docker Build

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: omnichannel-fitness-agent:pr-${{ github.event.pull_request.number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      #- name: Run tests
      #  run: |
      #    docker run --rm omnichannel-fitness-agent:pr-${{ github.event.pull_request.number }} pytest

      - name: Clean cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache